apiVersion: v1
kind: Pod
metadata:
  name: web
spec:
  containers:
    - name: contenedor1
      image: nginx:alpine
---
apiVersion: v1
kind: Pod
metadata:
  name: devops
spec:
  containers:
    - name: contenedor2
      image: jenkins/jenkins
