apiVersion: v1
kind: Service
metadata:
  name: frontend-svc
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 8081
      name: port1
    - protocol: TCP
      port: 8084
      targetPort: 8082
      name: port2
  type: ClusterIP
