apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-ms
  template:
    metadata:
      labels:
        app: auth-ms
    spec:
      containers:
        - name: auth-container
          image: 282865065290.dkr.ecr.us-east-1.amazonaws.com/auth-ms
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          env:
            - name: PORT
              value: "8000"
            - name: MONGO_HOST
              value: mongo-svc
            - name: MONGO_PORT
              value: "27017"
            - name: MONGO_USERNAME
              value: root
            - name: MONGO_PASSWORD
              value: root
            - name: MONGO_AUTH_SOURCE
              value: admin
            - name: JWT_SECRET
              value: 7cb2ed23-c321-409b-900b-b3342382c1db
            - name: JWT_EXPIRES
              value: "2000"
            - name: MONGO_DATABASE
              value: authdb
---
apiVersion: v1
kind: Service
metadata:
  name: auth-svc
spec:
  selector:
    app: auth-ms
  ports:
    - port: 80
      targetPort: 8000
      protocol: TCP
  type: ClusterIP
