apiVersion: apps/v1
kind: Deployment
metadata:
  name: delivery-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: delivery-ms
  template:
    metadata:
      labels:
        app: delivery-ms
    spec:
      containers:
        - name: delivery-container
          image: 282865065290.dkr.ecr.us-east-1.amazonaws.com/delivery-ms
          imagePullPolicy: Always
          ports:
            - containerPort: 8040
          env:
            - name: PORT
              value: "8040"
            - name: MONGO_HOST
              value: mongo-svc
            - name: MONGO_PORT
              value: "27017"
            - name: MONGO_USERNAME
              value: root
            - name: MONGO_PASSWORD
              value: root
            - name: MONGO_AUTH_SOURCE
              value: admin
            - name: EXCHANGE_NAME
              value: EXCHANGE-ORDER-COMPLETED
            - name: EXCHANGE_TYPE
              value: fanout
            - name: QUEUE_NAME
              value: QUEUE_ORDER_COMPLETED
            - name: QUEUE_NAME_RECEIVE_ORDER
              value: QUEUE_STORE_CREATED
            - name: EXCHANGE_NAME_REJECT
              value: EXCHANGE-ORDER-REJECTED
            - name: EXCHANGE_TYPE_REJECT
              value: topic
            - name: ROUTING_KEY_REJECT
              value: delivery.error
            - name: RABBITMQ_HOST
              value: rabbitmq-svc:5672
            - name: MONGO_DATABASE
              value: deliverydb
---
apiVersion: v1
kind: Service
metadata:
  name: delivery-svc
spec:
  selector:
    app: delivery-ms
  ports:
    - port: 80
      targetPort: 8040
      protocol: TCP
  type: ClusterIP
