version: "3.8"

services:
  order-ms:
    container_name: order-ms
    image: order-ms
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./environment/order.env
    ports:
      - "3500:3500"
    networks:
      - net-template
    depends_on:
      - mongo
      - rabbitmq

  mongo:
    image: mongo:3.6
    container_name: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongo-vol:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: test
    networks:
      - net-template

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "status"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - net-template

volumes:
  mongo-vol:

networks:
  net-template:
