apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway-ms
  template:
    metadata:
      labels:
        app: gateway-ms
    spec:
      containers:
        - name: gateway-container
          image: localhost:5000/gateway
          imagePullPolicy: Always
          ports:
            - containerPort: 8010
          env:
            - name: PORT
              value: "8010"
            - name: PATH_ORDER
              value: http://order-svc
            - name: PATH_AUTH
              value: http://auth-svc
---
apiVersion: v1
kind: Service
metadata:
  name: gateway-svc
spec:
  selector:
    app: gateway-ms
  ports:
    - port: 80
      targetPort: 8010
      protocol: TCP
  type: ClusterIP
