apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-ms
  template:
    metadata:
      labels:
        app: order-ms
    spec:
      containers:
        - name: order-container
          image: localhost:5000/order-ms
          imagePullPolicy: Always
          ports:
            - containerPort: 8020
          env:
            - name: PORT
              value: "8020"
            - name: MONGO_HOST
              value: mongo-svc
            - name: MONGO_PORT
              value: "27017"
            - name: MONGO_USERNAME
              value: root
            - name: MONGO_PASSWORD
              value: root
            - name: MONGO_AUTH_SOURCE
              value: admin
            - name: EXCHANGE_NAME
              value: EXCHANGE-ORDER-COMPLETED
            - name: EXCHANGE_TYPE
              value: fanout
            - name: QUEUE_NAME
              value: QUEUE_ORDER_CREATED
            - name: EXCHANGE_NAME_REJECT
              value: EXCHANGE-ORDER-REJECTED
            - name: EXCHANGE_TYPE_REJECT
              value: topic
            - name: ROUTING_KEY_REJECT
              value: "*.error"
            - name: RABBITMQ_HOST
              value: rabbitmq-svc:5672
            - name: MONGO_DATABASE
              value: orderdb
---
apiVersion: v1
kind: Service
metadata:
  name: order-svc
spec:
  selector:
    app: order-ms
  ports:
    - port: 80
      targetPort: 8020
      protocol: TCP
  type: ClusterIP
