apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-ms
  template:
    metadata:
      labels:
        app: payment-ms
    spec:
      containers:
        - name: payment-container
          image: localhost:5000/payment-ms
          imagePullPolicy: Always
          ports:
            - containerPort: 8030
          env:
            - name: PORT
              value: "8030"
            - name: MONGO_HOST
              value: mongo-svc
            - name: MONGO_PORT
              value: "27017"
            - name: MONGO_USERNAME
              value: root
            - name: MONGO_PASSWORD
              value: root
            - name: MONGO_AUTH_SOURCE
              value: admin
            - name: EXCHANGE_NAME
              value: EXCHANGE-ORDER-COMPLETED
            - name: EXCHANGE_TYPE
              value: fanout
            - name: QUEUE_NAME
              value: QUEUE_PAYMENT_CREATED
            - name: QUEUE_NAME_RECEIVE_ORDER
              value: QUEUE_ORDER_CREATED
            - name: EXCHANGE_NAME_REJECT
              value: EXCHANGE-ORDER-REJECTED
            - name: EXCHANGE_TYPE_REJECT
              value: topic
            - name: ROUTING_KEY_REJECT
              value: delivery.error,store.error
            - name: RABBITMQ_HOST
              value: rabbitmq-svc:5672
            - name: MONGO_DATABASE
              value: paymentdb
---
apiVersion: v1
kind: Service
metadata:
  name: payment-svc
spec:
  selector:
    app: payment-ms
  ports:
    - port: 80
      targetPort: 8030
      protocol: TCP
  type: ClusterIP
